#!/usr/bin/perl
use warnings;
use strict;
use autodie;

my %set;
my $debug = 0;
$| = 1;


while(defined $ARGV[0] && $ARGV[0] =~ /^-/) {
  $debug = shift @ARGV;
}

while (my $line = <>) {
  chomp $line;
  unless ( $debug || exists $set{$line}) {
    print "$line\n";
  }
  $set{$line} += 1;
}

if ($debug) {
  foreach my $l (keys(%set)) {
    my $count_str = "$set{$l} ";
    print STDOUT "$count_str$l\n";
  }
}
